version: "3"

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    networks:
      - proxy
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always

  cron:
    image: nextcloud:apache
    container_name: nextcloud_cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - proxy
    ports:
      - 10080:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=${CLOUD_DOMAIN}
      - OVERWRITEHOST=${CLOUD_DOMAIN}
      - NEXTCLOUD_HOSTNAME=${CLOUD_DOMAIN}
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`${CLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`${CLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=http"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      # Proxy from documentation
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/"

networks:
  proxy:
    external: true
